section .text

global interrupt_ISRCommonHandler
global interrupt_ISRCommonHandlerInjectionReturn

global interrupt_IRQCommonHandler

extern interrupt_InterruptHandlers_CommonISRHandler

extern interrupt_IRQ_CommonIRQHandler

%macro ISR_NOERRORCODE 1

	global interrupt_ISR%1

	interrupt_ISR%1:
		
		push 0
		push %1
		
		jmp interrupt_ISRCommonHandler

%endmacro

%macro ISR_ERRORCODE 1

	global interrupt_ISR%1

	interrupt_ISR%1:
		
		push %1
		
		jmp interrupt_ISRCommonHandler

%endmacro


ISR_NOERRORCODE 0x00
ISR_NOERRORCODE 0x01
ISR_NOERRORCODE 0x02
ISR_NOERRORCODE 0x03
ISR_NOERRORCODE 0x04
ISR_NOERRORCODE 0x05
ISR_NOERRORCODE 0x06
ISR_NOERRORCODE 0x07
ISR_ERRORCODE 0x08
ISR_NOERRORCODE 0x09
ISR_ERRORCODE 0x0A
ISR_ERRORCODE 0x0B
ISR_ERRORCODE 0x0C
ISR_ERRORCODE 0x0D
ISR_ERRORCODE 0x0E
ISR_NOERRORCODE 0x0F
ISR_NOERRORCODE 0x10
ISR_ERRORCODE 0x11
ISR_NOERRORCODE 0x12
ISR_NOERRORCODE 0x13
ISR_NOERRORCODE 0x14
ISR_NOERRORCODE 0x15
ISR_NOERRORCODE 0x16
ISR_NOERRORCODE 0x17
ISR_NOERRORCODE 0x18
ISR_NOERRORCODE 0x19
ISR_NOERRORCODE 0x1A
ISR_NOERRORCODE 0x1B
ISR_NOERRORCODE 0x1C
ISR_NOERRORCODE 0x1D
ISR_ERRORCODE 0x1E
ISR_NOERRORCODE 0x1F
ISR_NOERRORCODE 0x20
ISR_NOERRORCODE 0x21
ISR_NOERRORCODE 0x22
ISR_NOERRORCODE 0x23
ISR_NOERRORCODE 0x24
ISR_NOERRORCODE 0x25
ISR_NOERRORCODE 0x26
ISR_NOERRORCODE 0x27
ISR_NOERRORCODE 0x28
ISR_NOERRORCODE 0x29
ISR_NOERRORCODE 0x2A
ISR_NOERRORCODE 0x2B
ISR_NOERRORCODE 0x2C
ISR_NOERRORCODE 0x2D
ISR_NOERRORCODE 0x2E
ISR_NOERRORCODE 0x2F
ISR_NOERRORCODE 0x30
ISR_NOERRORCODE 0x31
ISR_NOERRORCODE 0x32
ISR_NOERRORCODE 0x33
ISR_NOERRORCODE 0x34
ISR_NOERRORCODE 0x35
ISR_NOERRORCODE 0x36
ISR_NOERRORCODE 0x37
ISR_NOERRORCODE 0x38
ISR_NOERRORCODE 0x39
ISR_NOERRORCODE 0x3A
ISR_NOERRORCODE 0x3B
ISR_NOERRORCODE 0x3C
ISR_NOERRORCODE 0x3D
ISR_NOERRORCODE 0x3E
ISR_NOERRORCODE 0x3F
ISR_NOERRORCODE 0x40
ISR_NOERRORCODE 0x41
ISR_NOERRORCODE 0x42
ISR_NOERRORCODE 0x43
ISR_NOERRORCODE 0x44
ISR_NOERRORCODE 0x45
ISR_NOERRORCODE 0x46
ISR_NOERRORCODE 0x47
ISR_NOERRORCODE 0x48
ISR_NOERRORCODE 0x49
ISR_NOERRORCODE 0x4A
ISR_NOERRORCODE 0x4B
ISR_NOERRORCODE 0x4C
ISR_NOERRORCODE 0x4D
ISR_NOERRORCODE 0x4E
ISR_NOERRORCODE 0x4F
ISR_NOERRORCODE 0x50
ISR_NOERRORCODE 0x51
ISR_NOERRORCODE 0x52
ISR_NOERRORCODE 0x53
ISR_NOERRORCODE 0x54
ISR_NOERRORCODE 0x55
ISR_NOERRORCODE 0x56
ISR_NOERRORCODE 0x57
ISR_NOERRORCODE 0x58
ISR_NOERRORCODE 0x59
ISR_NOERRORCODE 0x5A
ISR_NOERRORCODE 0x5B
ISR_NOERRORCODE 0x5C
ISR_NOERRORCODE 0x5D
ISR_NOERRORCODE 0x5E
ISR_NOERRORCODE 0x5F
ISR_NOERRORCODE 0x60
ISR_NOERRORCODE 0x61
ISR_NOERRORCODE 0x62
ISR_NOERRORCODE 0x63
ISR_NOERRORCODE 0x64
ISR_NOERRORCODE 0x65
ISR_NOERRORCODE 0x66
ISR_NOERRORCODE 0x67
ISR_NOERRORCODE 0x68
ISR_NOERRORCODE 0x69
ISR_NOERRORCODE 0x6A
ISR_NOERRORCODE 0x6B
ISR_NOERRORCODE 0x6C
ISR_NOERRORCODE 0x6D
ISR_NOERRORCODE 0x6E
ISR_NOERRORCODE 0x6F
ISR_NOERRORCODE 0x70
ISR_NOERRORCODE 0x71
ISR_NOERRORCODE 0x72
ISR_NOERRORCODE 0x73
ISR_NOERRORCODE 0x74
ISR_NOERRORCODE 0x75
ISR_NOERRORCODE 0x76
ISR_NOERRORCODE 0x77
ISR_NOERRORCODE 0x78
ISR_NOERRORCODE 0x79
ISR_NOERRORCODE 0x7A
ISR_NOERRORCODE 0x7B
ISR_NOERRORCODE 0x7C
ISR_NOERRORCODE 0x7D
ISR_NOERRORCODE 0x7E
ISR_NOERRORCODE 0x7F
ISR_NOERRORCODE 0x80
ISR_NOERRORCODE 0x81
ISR_NOERRORCODE 0x82
ISR_NOERRORCODE 0x83
ISR_NOERRORCODE 0x84
ISR_NOERRORCODE 0x85
ISR_NOERRORCODE 0x86
ISR_NOERRORCODE 0x87
ISR_NOERRORCODE 0x88
ISR_NOERRORCODE 0x89
ISR_NOERRORCODE 0x8A
ISR_NOERRORCODE 0x8B
ISR_NOERRORCODE 0x8C
ISR_NOERRORCODE 0x8D
ISR_NOERRORCODE 0x8E
ISR_NOERRORCODE 0x8F
ISR_NOERRORCODE 0x90
ISR_NOERRORCODE 0x91
ISR_NOERRORCODE 0x92
ISR_NOERRORCODE 0x93
ISR_NOERRORCODE 0x94
ISR_NOERRORCODE 0x95
ISR_NOERRORCODE 0x96
ISR_NOERRORCODE 0x97
ISR_NOERRORCODE 0x98
ISR_NOERRORCODE 0x99
ISR_NOERRORCODE 0x9A
ISR_NOERRORCODE 0x9B
ISR_NOERRORCODE 0x9C
ISR_NOERRORCODE 0x9D
ISR_NOERRORCODE 0x9E
ISR_NOERRORCODE 0x9F
ISR_NOERRORCODE 0xA0
ISR_NOERRORCODE 0xA1
ISR_NOERRORCODE 0xA2
ISR_NOERRORCODE 0xA3
ISR_NOERRORCODE 0xA4
ISR_NOERRORCODE 0xA5
ISR_NOERRORCODE 0xA6
ISR_NOERRORCODE 0xA7
ISR_NOERRORCODE 0xA8
ISR_NOERRORCODE 0xA9
ISR_NOERRORCODE 0xAA
ISR_NOERRORCODE 0xAB
ISR_NOERRORCODE 0xAC
ISR_NOERRORCODE 0xAD
ISR_NOERRORCODE 0xAE
ISR_NOERRORCODE 0xAF
ISR_NOERRORCODE 0xB0
ISR_NOERRORCODE 0xB1
ISR_NOERRORCODE 0xB2
ISR_NOERRORCODE 0xB3
ISR_NOERRORCODE 0xB4
ISR_NOERRORCODE 0xB5
ISR_NOERRORCODE 0xB6
ISR_NOERRORCODE 0xB7
ISR_NOERRORCODE 0xB8
ISR_NOERRORCODE 0xB9
ISR_NOERRORCODE 0xBA
ISR_NOERRORCODE 0xBB
ISR_NOERRORCODE 0xBC
ISR_NOERRORCODE 0xBD
ISR_NOERRORCODE 0xBE
ISR_NOERRORCODE 0xBF
ISR_NOERRORCODE 0xC0
ISR_NOERRORCODE 0xC1
ISR_NOERRORCODE 0xC2
ISR_NOERRORCODE 0xC3
ISR_NOERRORCODE 0xC4
ISR_NOERRORCODE 0xC5
ISR_NOERRORCODE 0xC6
ISR_NOERRORCODE 0xC7
ISR_NOERRORCODE 0xC8
ISR_NOERRORCODE 0xC9
ISR_NOERRORCODE 0xCA
ISR_NOERRORCODE 0xCB
ISR_NOERRORCODE 0xCC
ISR_NOERRORCODE 0xCD
ISR_NOERRORCODE 0xCE
ISR_NOERRORCODE 0xCF
ISR_NOERRORCODE 0xD0
ISR_NOERRORCODE 0xD1
ISR_NOERRORCODE 0xD2
ISR_NOERRORCODE 0xD3
ISR_NOERRORCODE 0xD4
ISR_NOERRORCODE 0xD5
ISR_NOERRORCODE 0xD6
ISR_NOERRORCODE 0xD7
ISR_NOERRORCODE 0xD8
ISR_NOERRORCODE 0xD9
ISR_NOERRORCODE 0xDA
ISR_NOERRORCODE 0xDB
ISR_NOERRORCODE 0xDC
ISR_NOERRORCODE 0xDD
ISR_NOERRORCODE 0xDE
ISR_NOERRORCODE 0xDF
ISR_NOERRORCODE 0xE0
ISR_NOERRORCODE 0xE1
ISR_NOERRORCODE 0xE2
ISR_NOERRORCODE 0xE3
ISR_NOERRORCODE 0xE4
ISR_NOERRORCODE 0xE5
ISR_NOERRORCODE 0xE6
ISR_NOERRORCODE 0xE7
ISR_NOERRORCODE 0xE8
ISR_NOERRORCODE 0xE9
ISR_NOERRORCODE 0xEA
ISR_NOERRORCODE 0xEB
ISR_NOERRORCODE 0xEC
ISR_NOERRORCODE 0xED
ISR_NOERRORCODE 0xEE
ISR_NOERRORCODE 0xEF
ISR_NOERRORCODE 0xF0
ISR_NOERRORCODE 0xF1
ISR_NOERRORCODE 0xF2
ISR_NOERRORCODE 0xF3
ISR_NOERRORCODE 0xF4
ISR_NOERRORCODE 0xF5
ISR_NOERRORCODE 0xF6
ISR_NOERRORCODE 0xF7
ISR_NOERRORCODE 0xF8
ISR_NOERRORCODE 0xF9
ISR_NOERRORCODE 0xFA
ISR_NOERRORCODE 0xFB
ISR_NOERRORCODE 0xFC
ISR_NOERRORCODE 0xFD
ISR_NOERRORCODE 0xFE
ISR_NOERRORCODE 0xFF

interrupt_ISRCommonHandler:

	pushad
	
	mov ax, ds
	push eax
	
	mov ax, 0x10
	mov ds, ax
	mov es, ax
	mov fs, ax
	mov gs, ax
	
	call interrupt_InterruptHandlers_CommonISRHandler
	
interrupt_ISRCommonHandlerInjectionReturn:
	
	pop eax
	mov ds, ax
	mov es, ax
	mov fs, ax
	mov gs, ax
	
	popad
	
	add esp, 8
	
	iret
	
	
